version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: withoutbg
    bump: patch

build:
  toolchains: []
  run_buildscript: false

images:
  - id: withoutbg
    target: service
    service: withoutbg
    source: docker.io/withoutbg/withoutbg-openweights-v3-service-cpu
    channel: custom
    sort: created
    tag_regex: '^latest$'
    delivery:
      mode: mirror
      require_digest_match: true

stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: WithoutBG
    summary: Background Removal API and Self-Hosted Model
