package: community.lazycat.app.withoutbg
version: 0.0.2
name: WithoutBG
description: Background Removal API and Self-Hosted Model
min_os_version: 1.5.0
homepage: https://withoutbg.com
author: WithoutBG
license: Apache-2.0
permissions:
  required:
    - net.internet
locales:
  zh:
    name: WithoutBG
    description: 可自托管模型的图片背景移除 API
  en:
    name: WithoutBG
    description: Background Removal API and Self-Hosted Model
